sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t joelclim/multi-docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true joelclim/multi-docker-test npm test

after_success:
  - docker build -t joelclim/multi-docker-client-production ./client
  - docker build -t joelclim/multi-docker-nginx-production ./nginx
  - docker build -t joelclim/multi-docker-server-production ./server
  - docker build -t joelclim/multi-docker-worker-production ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push joelclim/multi-docker-client-production
  - docker push joelclim/multi-docker-nginx-production
  - docker push joelclim/multi-docker-server-production
  - docker push joelclim/multi-docker-worker-production
